language: node_js

node_js:
  - node

# addons:
#   ssh_known_hosts: $DEPLOY_HOST

before_install:
  # manually add known hosts (addons -> ssh_known_hosts wont do it :-( )
  - ssh-keyscan -t rsa $DEPLOY_HOST 2> /dev/null | sort -u - ~/.ssh/known_hosts -o ~/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_f5244851a833_key -iv $encrypted_f5244851a833_iv -in deploy_key.enc -out deploy_key -d
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 deploy_key # this key should have push access
  - ssh-add deploy_key

install:
  - npm install

script:
  - npm run build
  - mkdir build && cp -r static templates parsapp.py database.py reset_db.py build

after_success:
  - '[ "${TRAVIS_BRANCH}" = "master" ] && rsync -rq build/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH'
