language: node_js

node_js:
  - node

addons:
  ssh_known_hosts: $DEPLOY_HOST

before_install:
  - openssl aes-256-cbc -K $encrypted_1017bbc80658_key -iv $encrypted_1017bbc80658_iv -in deploy_key.enc -out deploy_key -d
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 deploy_key # this key should have push access
  - ssh-add deploy_key

install:
  - npm install

script:
  - npm run build
  - mkdir build && cp -r static templates parsapp.py database.py build

after_success:
  - '[ "${TRAVIS_BRANCH}" = "master" ] && rsync -rqe "ssh -o StrictHostKeyChecking=no" build/ $DEPLOY_USER@$DEPLOY_HOST:'
